name: IOTrails
main: com.interordi.iotrails.IOTrails
version: 1.3
api-version: 1.13

commands:
  trail:
    description: View or use a trail
    usage: /trail
  trails:
    description: View or use a trail
    usage: /trails
